name: Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v6

    - name: Fix gradlew
      run: |
        sudo apt-get update && sudo apt-get install -y dos2unix
        dos2unix gradlew
        chmod +x gradlew

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 11
        cache: gradle

    - name: Setup NDK + CMake
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: false

    - name: Build module
      run: |
        echo "=== NDK Path ==="
        echo $ANDROID_NDK_ROOT
        
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        
        ./gradlew :module:assembleRelease --stacktrace
